$ANSIBLE_VAULT;1.1;AES256
35373639373462303338626130316265636539396163653238623033336634633434363531393766
3261346634663630656235643537653131313265626531310a623430393165373733653462363661
38663762646531383765393138663862653736623061373164336136663662653634383732636339
3465323932313362340a333763383430653962666236366630396666653434313832646432336664
37336239353435323530323031613634636434353832306461373734623437646363343966333833
39306565616234343665383331323031333132616262323438363863613461363738343231623164
30653365326339356235623335376134323461353031303965643932623633393935303861363433
31316633663532666334663561333439343865306337646335303438623263393565363734623030
33663337623639363236643034396164396638393732373833346539383064343830
